// Generated by Strav — DO NOT EDIT
import { DateTime } from "luxon";
import BaseModel from "@strav/database/orm/base_model";
import { primary } from "@strav/database/orm/decorators";

export default class Conversation extends BaseModel {
  static override softDeletes = true;

  @primary
  declare id: string;

  declare visitorId: string | null;
  declare sessionId: string;
  declare context: Record<string, unknown> | null;
  declare metadata: Record<string, unknown> | null;
  status: string = "active";

  declare createdAt: DateTime;
  declare updatedAt: DateTime;
  declare deletedAt: DateTime | null;
}
