// Generated by Strav — DO NOT EDIT
import { DateTime } from "luxon";
import BaseModel from "@strav/database/orm/base_model";
import { primary, reference } from "@strav/database/orm/decorators";
import { MessageRole } from "../../enums/public/message";
import type Conversation from "./conversation";

export default class Message extends BaseModel {
  @primary
  declare id: string;

  declare conversationId: string;

  declare role: MessageRole;
  declare content: string;
  declare metadata: Record<string, unknown> | null;
  isTyping: boolean = false;

  declare createdAt: DateTime;
  declare updatedAt: DateTime;

  @reference({
    model: "Conversation",
    foreignKey: "conversationId",
    targetPK: "id",
  })
  declare conversation: Conversation;
}
