// Generated by Strav — DO NOT EDIT
import { DateTime } from "luxon";
import BaseModel from "@strav/database/orm/base_model";
import { primary } from "@strav/database/orm/decorators";

export default class User extends BaseModel {
  static override softDeletes = true;

  @primary
  declare id: number;

  declare email: string;
  declare name: string;
  declare password: string;

  declare createdAt: DateTime;
  declare updatedAt: DateTime;
  declare deletedAt: DateTime | null;
}
