// Generated by Strav — DO NOT EDIT
import { DateTime } from "luxon";
import BaseModel from "@strav/database/orm/base_model";
import { primary } from "@strav/database/orm/decorators";
import { VisitorDeviceType } from "../../enums/public/visitor";

export default class Visitor extends BaseModel {
  static override softDeletes = true;

  @primary
  declare id: string;

  declare ipAddress: string | null;
  declare userAgent: string | null;
  declare referrer: string | null;
  declare country: string | null;
  declare city: string | null;
  declare deviceType: VisitorDeviceType | null;
  declare browser: string | null;
  declare os: string | null;
  declare preferences: Record<string, unknown> | null;
  declare metadata: Record<string, unknown> | null;

  declare createdAt: DateTime;
  declare updatedAt: DateTime;
  declare deletedAt: DateTime | null;
}
